name: Install ArgoCD

on: 
  workflow_call:
    inputs:
      aks_name:
        description: "Name of the AKS cluster"
        required: true
        type: string
      rg_name:
        description: "Name of the Resource Group"
        required: true
        type: string


jobs:
  argocd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Azure CLI
        run: az upgrade --yes

      
      - name: Remove preinstalled Azure CLI
        run: sudo apt-get remove -y azure-cli

      - name: Install Azure CLI 2.76.0
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          sudo apt-get install -y --allow-downgrades azure-cli=2.76.0-1~noble


      
      - name: Get AKS credentials
        run: |
          az aks get-credentials \
          --resource-group "${{ inputs.rg_name }}" \
          --name "${{ inputs.aks_name }}" \
          --overwrite-existing \
          --admin



      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Create ArgoCD namespace
        run: kubectl create namespace argocd || true

      - name: Install ArgoCD via Helm
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          helm install argocd argo/argo-cd \
            --namespace argocd \
            --create-namespace \
            --set server.service.type=ClusterIP

      - name: Wait for ArgoCD server
        run: kubectl rollout status deployment argocd-server -n argocd --timeout=180s

      - name: Apply ArgoCD Application
        run: kubectl apply -f argocd/petapp-app.yaml
