name: Install ArgoCD

on: 
  workflow_call:
    inputs:
      aks_name:
        description: "Name of the AKS cluster"
        required: true
        type: string
      rg_name:
        description: "Name of the Resource Group"
        required: true
        type: string


jobs:
  argocd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.AKS_KUBECONFIG_B64 }}" | base64 --decode > $HOME/.kube/config


      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Create ArgoCD namespace
        run: kubectl create namespace argocd || true

      - name: Install ArgoCD via Helm
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            --create-namespace \
            --set server.service.type=LoadBalancer

      - name: Wait for ArgoCD server
        run: kubectl rollout status deployment argocd-server -n argocd --timeout=180s

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          argocd version --client

      - name: Login to ArgoCD
        run: |
          EXTERNAL_IP=$(kubectl get svc -n argocd argocd-server -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          argocd login $EXTERNAL_IP \
          --username admin \
          --password $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d) \
          --insecure

      - name: Sync ArgoCD Application
        run: argocd app sync petapp


      # - name: Apply ArgoCD Application
      #   run: kubectl apply -f argocd/petapp-app.yml
