name: Terraform Apply

on:
  workflow_call:
    outputs:
      aks_name:
        description: "AKS cluster name"
        value: ${{ jobs.terraform.outputs.aks_name }}
      rg_name:
        description: "Resource group"
        value: ${{ jobs.terraform.outputs.rg_name }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    outputs:
      aks_name: ${{ steps.get_outputs.outputs.aks_name }}
      rg_name: ${{ steps.get_outputs.outputs.rg_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set SP env vars for Terraform
        run: |
          echo "ARM_CLIENT_ID=$(jq -r .clientId <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(jq -r .tenantId <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # --- INIT FIRST ---
      - name: Terraform Init Bootstrap
        working-directory: infra/bootstrap
        run: terraform init -input=false

        # --- IMPORT EXISTING RESOURCES ---
      - name: Import existing RG
        working-directory: infra/bootstrap
        run: |
          if az group show -n my_rg >/dev/null 2>&1; then
            terraform import azurerm_resource_group.tfstate_rg /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/my_rg
          else
            echo "No existing RG"
          fi

      - name: Import existing Storage Account
        working-directory: infra/bootstrap
        run: |
          if az storage account show -n tfstatestorage420 -g my_rg >/dev/null 2>&1; then
            terraform import azurerm_storage_account.tfstatestorage420 /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/my_rg/providers/Microsoft.Storage/storageAccounts/tfstatestorage420
          else
            echo "No existing storage account"
          fi

      - name: Import existing Storage Container
        working-directory: infra/bootstrap
        run: |
          if az storage container exists --name terraform-state --account-name tfstatestorage420 | grep true; then
            terraform import azurerm_storage_container.tfstate_container /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/my_rg/providers/Microsoft.Storage/storageAccounts/tfstatestorage420/blobServices/default/containers/terraform-state
          else
            echo "No existing container"
          fi

        # --- APPLY BOOTSTRAP ---
      - name: Terraform Bootstrap Apply
        working-directory: infra/bootstrap
        run: terraform apply -auto-approve -input=false

        # --- INIT & APPLY AKS ---
      - name: Terraform Init AKS
        working-directory: infra/aks
        run: terraform init -reconfigure -input=false

      - name: Terraform AKS Apply
        working-directory: infra/aks
        run: terraform apply -auto-approve -input=false

        

  
      # --- CAPTURE OUTPUTS ---
      - name: Get Terraform Outputs
        id: get_outputs
        run: |
          echo "aks_name=$(terraform -chdir=infra/aks output -raw aks_name)" >> $GITHUB_OUTPUT
          echo "rg_name=$(terraform -chdir=infra/aks output -raw rg_name)" >> $GITHUB_OUTPUT
